# Generated by Django 5.1.6 on 2025-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
