# Generated by Django 5.1.6 on 2025-03-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_cart_user_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
