# Generated by Django 5.1.6 on 2025-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_remove_category_image_remove_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
