# Generated by Django 5.1.6 on 2025-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_alter_category_image_url_alter_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
